### ISSUE TITLE
图片合成问题

### ISSUE THREAD

**Issue by StarcraftSu** [lijinke666/react-image-process#7]
您好，

我是在你的博客上留言的匿名人，我想要做的是把上传的Logo作为水印加在上传的图片中。我已经用antd把图片都转成了Base64格式，但不知道如何使用你的插件来合成图片。代码如下：
为了看起来更方便一点，我也会上传截图

<ReactImageProcess
              mode="waterMark"
              waterMarkType="image"
              waterMark={this.state.base64Logo}
              opacity={0.7}
              coordinate={[0, 0]}
               >
               <img
                      style={{
                            maxWidth:'100%',
                            maxHeight: '100%',
                            display: this.state.base64Img?'block':'none',
                            margin:'0 auto'
                         }}
                            src={this.state.base64Img}
                            alt="waterMark"
                  />
</ReactImageProcess>

**Comment by StarcraftSu** [comment]
<img width="421" alt="issue" src="https://user-images.githubusercontent.com/31477900/62464488-56898380-b7bf-11e9-9691-dfe635a62472.png">

**Comment by lijinke666** [comment]
你 贴的代码 有什么问题
合成不了 具体是什么合成不了
完整的代码是啥？
控制台报错了吗 报的什么错？

**Comment by StarcraftSu** [comment]
感谢帮忙。
贴的代码本身没什么问题，如果watermark属性和img的src引入的是静态图片链接，ReactImgProcess组件是可以正常的渲染出合成的水印图片。但是，如果是用户上传图片，然后转换成base64 URL格式，再引入到ReactImgProcess组件中就不能正常渲染。控台没有报错，有时候渲染会卡死。我上传完整代码（压缩的JS组件）。

AddWaterMark是父组件
UploadImg是子组件

[Source.zip](https://github.com/lijinke666/react-image-process/files/3469977/Source.zip)

**Comment by lijinke666** [comment]
我有空看看吧,估计是生命周期的问题 太忙了 如果你很急 用原生就可以实现 代码也很简单

```js
	const getImage = (src) => new Promise((res,rej)=>{
			const img = new Image()
			img.src = src
			img.onload = () => res(img)
 			img.onerror = rej
		})
 aysnc function test () {
        const canvas = document.createElement('canvas');

		const logo = await getImage(this.state.base64Logo)
        const img = await getImage(this.state.base64Img)
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        ctx.drawImage(logo)
		return Promise.resolve(new File([canvas.toDataURL('image/png')],'filename'))
 }
```

**Comment by StarcraftSu** [comment]
好的 多谢
